### ISSUE TITLE
UDP echo: error while using make on macOS

### ISSUE THREAD

**Issue by noahhorn** [rbultman/raspberry-jam#28]
Hello, thank you so much for writing this code, I've been searching for a program like this for a long time.
I tried to run this on the latest macOS Catalina, and got the following error message:

<pre>noah@5K udp-echo % make
gcc -o udpclient udpclient.c
udpclient.c:110:13: error: use of undeclared identifier 'MSG_CONFIRM'
            MSG_CONFIRM, (const struct sockaddr *) &servaddr, 
            ^
udpclient.c:130:16: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
               &len); 
               ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:703:27: note: passing argument to parameter here
    socklen_t * __restrict) __DARWIN_ALIAS_C(recvfrom);
                          ^
1 warning and 1 error generated.
make: *** [udpclient] Error 1
noah@5K udp-echo % 
</pre>

I will look into this more when I can — maybe it needs another library include for macOS users?

Edit: <a href="https://stackoverflow.com/questions/50751894/udp-client-on-a-os-x">This Stack Overflow question</a> applies to the exact same code base (geeksforgeeks.org), and <a href="https://stackoverflow.com/questions/23472533/recvfrom-not-filling-the-from-ip-address-even-for-udp-messages-in-first-call">this earlier Stack Overflow question</a> references a similar issue.

Edit 2: I've tried a few different lines after <code>int n, len</code> in udpclient.c line 105, such as:
<code>	len = sizeof(servaddr);</code>
but nothing helps so far.

**Comment by omarcostahamido** [comment]
Confirming this. Simply running the [building instructions](https://github.com/rbultman/raspberry-jam/blob/develop/udp-echo/README.md#building), won't work on osx 10.15.3:

```
$  make
gcc -o udpclient udpclient.c
udpclient.c:110:13: error: use of undeclared identifier 'MSG_CONFIRM'
            MSG_CONFIRM, (const struct sockaddr *) &servaddr, 
            ^
udpclient.c:130:16: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *')
      converts between pointers to integer types with different sign [-Wpointer-sign]
               &len); 
               ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:703:27: note: 
      passing argument to parameter here
    socklen_t * __restrict) __DARWIN_ALIAS_C(recvfrom);
                          ^
1 warning and 1 error generated.
make: *** [udpclient] Error 1
```

**Comment by rbultman** [comment]
Thanks @noahhorn, I'll see if I can fix it.

**Comment by omarcostahamido** [comment]
@rbultman great.
I was starting to look around me self: 
```
$  git log -SMSG_CONFIRM
commit db0939a080433a571a3ca2c42dae43e7a0768243 (tag: v1.1)
Author: Rob Bultman <rob@firstbuild.com>
Date:   Wed May 27 10:04:44 2020 -0400

    Added udp puncher

commit a85dd578bd24e7f3749c9c442a6314db03b006eb
Author: Rob Bultman <rob@firstbuild.com>
Date:   Tue May 26 15:42:35 2020 -0400

    Adding latency measurer
```
but you'll probably figure it out way faster 🥇

**Comment by rbultman** [comment]
@noahhorn, I've got it compiling on OSX and Raspberry Pi.  Please pull and confirm. Thanks.

**Comment by noahhorn** [comment]
:) wonderful, thank you! Works perfectly.
Would love to have the port configurable via command line eventually. But this is excellent!!

**Comment by omarcostahamido** [comment]
I'm not @noahhorn , but I can at least confirm it went through the building steps.

```
$  make
gcc -D MACH_OSX -o udpclient udpclient.c
gcc -D MACH_OSX -o udpserver udpserver.c
```

👍

**Comment by rbultman** [comment]
Thanks for confirming too @omarcostahamido!
